; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "VeneraNext"
#define MyAppVersion "{{version}}"
#define MyAppPublisher "CyrilPeng/venera-next"
#define MyAppURL "https://github.com/CyrilPeng/venera-next"
#define MyAppExeName "VeneraNext.exe"
#define RootPath "{{root_path}}"

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  OldVersionPath, ShortcutPath: string;
begin
  if CurStep = ssInstall then
  begin
    OldVersionPath := 'C:\Program Files (x86)\Venera';
    if DirExists(OldVersionPath) then
    begin
      DelTree(OldVersionPath, True, True, True);
      ShortcutPath := GetEnv('USERPROFILE') + '\Desktop\Venera.lnk';
      if FileExists(ShortcutPath) then
      begin
        DeleteFile(ShortcutPath);
      end;
      ShortcutPath := 'C:\Users\Public\Desktop\Venera.lnk';
      if FileExists(ShortcutPath) then
      begin
        DeleteFile(ShortcutPath);
      end;
    end;
  end;
end;

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C6B7E69A-0FD6-4F2A-AC64-7D1AE8A40FB8}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#RootPath}\build\windows
OutputBaseFilename=VeneraNext-{#MyAppVersion}-windows-installer
SetupIconFile={#RootPath}\windows\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "{#RootPath}\windows\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Flutter may add native plugin libraries as dependencies. Include the complete
; release directory so new DLLs cannot be omitted from the installer.
Source: "{#RootPath}\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall
