import 'dart:async';

import 'package:venera_next/foundation/appdata.dart';
import 'package:venera_next/features/comic_source/comic_source.dart';

/// Picks the most frequent content tags from search results.
///
/// Empty strings, URLs and over-long entries are ignored. Ties are ordered
/// alphabetically so the result is deterministic.
List<String> topArtistTags(List<Comic> comics, {int limit = 5}) {
  var counts = <String, int>{};
  for (var comic in comics) {
    for (var tag in comic.tags ?? const <String>[]) {
      var t = tag.trim();
      if (t.isEmpty || t.length > 30 || t.contains('http')) continue;
      counts[t] = (counts[t] ?? 0) + 1;
    }
  }
  var entries = counts.entries.toList()
    ..sort((a, b) {
      var byCount = b.value.compareTo(a.value);
      if (byCount != 0) return byCount;
      return a.key.compareTo(b.key);
    });
  return entries.take(limit).map((e) => e.key).toList();
}

/// Cached artist profile: top tags generated by [analyzeArtistProfile].
Map<String, dynamic>? getArtistProfile(String name) {
  var raw = appdata.settings['artistProfiles'];
  if (raw is! Map) return null;
  var value = raw[name];
  if (value is! Map) return null;
  return Map<String, dynamic>.from(value);
}

void setArtistProfile(String name, List<String> tags) {
  var raw = appdata.settings['artistProfiles'];
  var map = raw is Map ? Map<String, dynamic>.from(raw) : <String, dynamic>{};
  map[name] = {
    'tags': tags,
    'updatedAt': DateTime.now().millisecondsSinceEpoch,
  };
  appdata.settings['artistProfiles'] = map;
  unawaited(appdata.saveData());
}

void removeArtistProfile(String name) {
  var raw = appdata.settings['artistProfiles'];
  if (raw is! Map) return;
  var map = Map<String, dynamic>.from(raw)..remove(name);
  appdata.settings['artistProfiles'] = map;
  unawaited(appdata.saveData());
}

/// Searches [name] across all sources and returns the top content tags.
Future<List<String>> analyzeArtistProfile(String name) async {
  var comics = <Comic>[];
  for (var source in ComicSource.all()) {
    var search = source.searchPageData;
    if (search?.loadPage == null) continue;
    try {
      var res = await search!.loadPage!(name, 0, const []);
      comics.addAll(res.dataOrNull ?? const []);
    } catch (e) {
      // A failing source should not block the others.
    }
  }
  return topArtistTags(comics);
}

/// Analyzes [name] in the background and caches the profile.
///
/// Silent: failures and empty results are ignored so background auto
/// analysis never interrupts the user.
Future<void> autoAnalyzeArtist(String name) async {
  if (getArtistProfile(name) != null) return;
  try {
    var tags = await analyzeArtistProfile(name);
    if (tags.isEmpty) return;
    setArtistProfile(name, tags);
  } catch (e) {
    // Silent by design.
  }
}
