name: 校验 Fastlane 元数据

on:
  workflow_dispatch:
  push:
      branches: [ "main" ]
      paths:
        - 'fastlane/**'
  pull_request:
      branches: [ "main" ]
      paths:
        - 'fastlane/**'

concurrency:
  group: fastlane-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - name: 校验 Fastlane Supply 元数据
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2.1.0
